log:
  level: 5
  output:
  path:
  sentry_dsn:
  extra_content:

db:
  db_name: "yibai"
  username: "root"
  password: "wentao"
  host: "127.0.0.1"
  port: 3306
  max_idle: 100
  max_conn: 1000
  max_life_time: 30
  auto_migrate: false
  enable_log: true
  log_type:


micro:
  service_name: "rpc_server_demo"
  etcd_addrs:
    - "127.0.0.1:12379"
  service_version:
  service_addr:
  transport:
  selector:
  consul_addrs:
  k8s_addrs:
  nats_addrs:

