log:
  level: 1
  output: "file"
  path: "/Users/wt/github/src/go_micro/server_one/"
  sentry_dsn:
  extra_content: "sdfsf"

db:
  db_name: "yibai"
  username: "root"
  password: "wentao"
  host: "127.0.0.1"
  port: 3306
  max_idle: 100
  max_conn: 1000
  max_life_time: 30
  auto_migrate: false
  enable_log: true
  log_type:


micro:
  etcd_addrs:
    - "127.0.0.1:12379"

