// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go_micro/golib/protoc/login/login.proto

package pblogin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyUserTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserTokenReq) Reset()         { *m = VerifyUserTokenReq{} }
func (m *VerifyUserTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyUserTokenReq) ProtoMessage()    {}
func (*VerifyUserTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_37e82f42ff47c968, []int{0}
}

func (m *VerifyUserTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserTokenReq.Unmarshal(m, b)
}
func (m *VerifyUserTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyUserTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserTokenReq.Merge(m, src)
}
func (m *VerifyUserTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyUserTokenReq.Size(m)
}
func (m *VerifyUserTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserTokenReq proto.InternalMessageInfo

func (m *VerifyUserTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyUserTokenResp struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserTokenResp) Reset()         { *m = VerifyUserTokenResp{} }
func (m *VerifyUserTokenResp) String() string { return proto.CompactTextString(m) }
func (*VerifyUserTokenResp) ProtoMessage()    {}
func (*VerifyUserTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_37e82f42ff47c968, []int{1}
}

func (m *VerifyUserTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserTokenResp.Unmarshal(m, b)
}
func (m *VerifyUserTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserTokenResp.Marshal(b, m, deterministic)
}
func (m *VerifyUserTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserTokenResp.Merge(m, src)
}
func (m *VerifyUserTokenResp) XXX_Size() int {
	return xxx_messageInfo_VerifyUserTokenResp.Size(m)
}
func (m *VerifyUserTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserTokenResp proto.InternalMessageInfo

func (m *VerifyUserTokenResp) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *VerifyUserTokenResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifyUserTokenResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*VerifyUserTokenReq)(nil), "pblogin.VerifyUserTokenReq")
	proto.RegisterType((*VerifyUserTokenResp)(nil), "pblogin.VerifyUserTokenResp")
}

func init() {
	proto.RegisterFile("go_micro/golib/protoc/login/login.proto", fileDescriptor_37e82f42ff47c968)
}

var fileDescriptor_37e82f42ff47c968 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xcf, 0x8f, 0xcf,
	0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x4f, 0xcf, 0xcf, 0xc9, 0x4c, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0x4f, 0xd6, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0x83, 0x90, 0x7a, 0x60, 0x21, 0x21, 0xf6, 0x82, 0x24,
	0x30, 0x57, 0x49, 0x8b, 0x4b, 0x28, 0x2c, 0xb5, 0x28, 0x33, 0xad, 0x32, 0xb4, 0x38, 0xb5, 0x28,
	0x24, 0x3f, 0x3b, 0x35, 0x2f, 0x28, 0xb5, 0x50, 0x48, 0x84, 0x8b, 0xb5, 0x04, 0xc4, 0x96, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0xe2, 0xb9, 0x84, 0x31, 0xd4, 0x16, 0x17, 0x08,
	0x49, 0x72, 0x71, 0x64, 0x16, 0xc7, 0x97, 0x25, 0xe6, 0x64, 0xa6, 0x80, 0xd5, 0x73, 0x04, 0xb1,
	0x67, 0x16, 0x87, 0x81, 0xb8, 0x08, 0x73, 0x98, 0x90, 0xcc, 0x11, 0x12, 0xe7, 0x62, 0x2f, 0x2d,
	0x4e, 0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0x03, 0x71, 0x3d,
	0x53, 0x8c, 0xf8, 0xb8, 0x78, 0x7c, 0x40, 0xae, 0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x4d,
	0x62, 0x03, 0x3b, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x1b, 0xb8, 0x69, 0xd7, 0x00,
	0x00, 0x00,
}
