// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: go_micro/golib/protoc/login/login.proto

package pblogin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for LoginService service

type LoginService interface {
}

type loginService struct {
	c    client.Client
	name string
}

func NewLoginService(name string, c client.Client) LoginService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pblogin"
	}
	return &loginService{
		c:    c,
		name: name,
	}
}

// Server API for LoginService service

type LoginServiceHandler interface {
}

func RegisterLoginServiceHandler(s server.Server, hdlr LoginServiceHandler, opts ...server.HandlerOption) error {
	type loginService interface {
	}
	type LoginService struct {
		loginService
	}
	h := &loginServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LoginService{h}, opts...))
}

type loginServiceHandler struct {
	LoginServiceHandler
}
