log:
  level: 5
  output:
  path:
  sentry_dsn:
  extra_content:

http:
  host: "127.0.0.1:9991"
  rate_per_second: 2000
  time_out: 20

micro:
  etcd_addrs:
    - "127.0.0.1:2379"

open_tracing:
  disable: false
  service_name: "api_gateway"
  agent_addr: "127.0.0.1:6831"

metrics:
  diable: false
  namespace: wbfex
  subsystem: apigateway
  metrics_path: "/metrics"

