// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: go_micro/golib/protoc/server_one/server_one.proto

package pbserverone

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	GetUserByUserName(ctx context.Context, in *GetUserByUserNameReq, opts ...client.CallOption) (*GetUserByUserNameResp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pbserverone"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUserByUserName(ctx context.Context, in *GetUserByUserNameReq, opts ...client.CallOption) (*GetUserByUserNameResp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByUserName", in)
	out := new(GetUserByUserNameResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetUserByUserName(context.Context, *GetUserByUserNameReq, *GetUserByUserNameResp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetUserByUserName(ctx context.Context, in *GetUserByUserNameReq, out *GetUserByUserNameResp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetUserByUserName(ctx context.Context, in *GetUserByUserNameReq, out *GetUserByUserNameResp) error {
	return h.UserServiceHandler.GetUserByUserName(ctx, in, out)
}
